services:
  futunurse:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/futunurse
    
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - futunurse_mongodb_data:/data/db
  
volumes:
  futunurse_mongodb_data: